/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1CommandRouteImport } from './routes/api/v1/command'
import { Route as ApiV1EventsRouteImport } from './routes/api/v1/events'
import { Route as ApiV1FleetRouteImport } from './routes/api/v1/fleet'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1RemediateRouteImport } from './routes/api/v1/remediate'
import { Route as ApiV1StreamRouteImport } from './routes/api/v1/stream'
import { Route as ApiV1TelemetryRouteImport } from './routes/api/v1/telemetry'
import { Route as ApiV1WebhooksMondayRouteImport } from './routes/api/v1/webhooks/monday'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CommandRoute = ApiV1CommandRouteImport.update({
  id: '/api/v1/command',
  path: '/api/v1/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EventsRoute = ApiV1EventsRouteImport.update({
  id: '/api/v1/events',
  path: '/api/v1/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FleetRoute = ApiV1FleetRouteImport.update({
  id: '/api/v1/fleet',
  path: '/api/v1/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RemediateRoute = ApiV1RemediateRouteImport.update({
  id: '/api/v1/remediate',
  path: '/api/v1/remediate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StreamRoute = ApiV1StreamRouteImport.update({
  id: '/api/v1/stream',
  path: '/api/v1/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TelemetryRoute = ApiV1TelemetryRouteImport.update({
  id: '/api/v1/telemetry',
  path: '/api/v1/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WebhooksMondayRoute = ApiV1WebhooksMondayRouteImport.update({
  id: '/api/v1/webhooks/monday',
  path: '/api/v1/webhooks/monday',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/v1/command': typeof ApiV1CommandRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/fleet': typeof ApiV1FleetRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/remediate': typeof ApiV1RemediateRoute
  '/api/v1/stream': typeof ApiV1StreamRoute
  '/api/v1/telemetry': typeof ApiV1TelemetryRoute
  '/api/v1/webhooks/monday': typeof ApiV1WebhooksMondayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/v1/command': typeof ApiV1CommandRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/fleet': typeof ApiV1FleetRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/remediate': typeof ApiV1RemediateRoute
  '/api/v1/stream': typeof ApiV1StreamRoute
  '/api/v1/telemetry': typeof ApiV1TelemetryRoute
  '/api/v1/webhooks/monday': typeof ApiV1WebhooksMondayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/v1/command': typeof ApiV1CommandRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/fleet': typeof ApiV1FleetRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/remediate': typeof ApiV1RemediateRoute
  '/api/v1/stream': typeof ApiV1StreamRoute
  '/api/v1/telemetry': typeof ApiV1TelemetryRoute
  '/api/v1/webhooks/monday': typeof ApiV1WebhooksMondayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/v1/command'
    | '/api/v1/events'
    | '/api/v1/fleet'
    | '/api/v1/health'
    | '/api/v1/remediate'
    | '/api/v1/stream'
    | '/api/v1/telemetry'
    | '/api/v1/webhooks/monday'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/v1/command'
    | '/api/v1/events'
    | '/api/v1/fleet'
    | '/api/v1/health'
    | '/api/v1/remediate'
    | '/api/v1/stream'
    | '/api/v1/telemetry'
    | '/api/v1/webhooks/monday'
  id:
    | '__root__'
    | '/'
    | '/api/v1/command'
    | '/api/v1/events'
    | '/api/v1/fleet'
    | '/api/v1/health'
    | '/api/v1/remediate'
    | '/api/v1/stream'
    | '/api/v1/telemetry'
    | '/api/v1/webhooks/monday'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiV1CommandRoute: typeof ApiV1CommandRoute
  ApiV1EventsRoute: typeof ApiV1EventsRoute
  ApiV1FleetRoute: typeof ApiV1FleetRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1RemediateRoute: typeof ApiV1RemediateRoute
  ApiV1StreamRoute: typeof ApiV1StreamRoute
  ApiV1TelemetryRoute: typeof ApiV1TelemetryRoute
  ApiV1WebhooksMondayRoute: typeof ApiV1WebhooksMondayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/command': {
      id: '/api/v1/command'
      path: '/api/v1/command'
      fullPath: '/api/v1/command'
      preLoaderRoute: typeof ApiV1CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/events': {
      id: '/api/v1/events'
      path: '/api/v1/events'
      fullPath: '/api/v1/events'
      preLoaderRoute: typeof ApiV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/fleet': {
      id: '/api/v1/fleet'
      path: '/api/v1/fleet'
      fullPath: '/api/v1/fleet'
      preLoaderRoute: typeof ApiV1FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/remediate': {
      id: '/api/v1/remediate'
      path: '/api/v1/remediate'
      fullPath: '/api/v1/remediate'
      preLoaderRoute: typeof ApiV1RemediateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/stream': {
      id: '/api/v1/stream'
      path: '/api/v1/stream'
      fullPath: '/api/v1/stream'
      preLoaderRoute: typeof ApiV1StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/telemetry': {
      id: '/api/v1/telemetry'
      path: '/api/v1/telemetry'
      fullPath: '/api/v1/telemetry'
      preLoaderRoute: typeof ApiV1TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/webhooks/monday': {
      id: '/api/v1/webhooks/monday'
      path: '/api/v1/webhooks/monday'
      fullPath: '/api/v1/webhooks/monday'
      preLoaderRoute: typeof ApiV1WebhooksMondayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiV1CommandRoute: ApiV1CommandRoute,
  ApiV1EventsRoute: ApiV1EventsRoute,
  ApiV1FleetRoute: ApiV1FleetRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1RemediateRoute: ApiV1RemediateRoute,
  ApiV1StreamRoute: ApiV1StreamRoute,
  ApiV1TelemetryRoute: ApiV1TelemetryRoute,
  ApiV1WebhooksMondayRoute: ApiV1WebhooksMondayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
